### PR TITLE
Added an example for redacted vcon

### PR DESCRIPTION
**Pull request by harippriyas**
* Added examples/redact.py to redact dialog texts and add it to the vcon as analysis object(s).
* Renamed the googlemeet recording file name to be windows compatible, so that git pull works on windows.

### CODE REVIEW

**Comment by harippriyas** [comment]
@dgpetrie any input on these build failures? they dont look related to the changes in this PR. Appreciate any pointers, thanks!

**Comment by dgpetrie** [comment]
Several of the failures are due to the the Deepgram and OpenAI keys are not set.

**Comment by harippriyas** [comment]
Oh ok, how to set these keys for automated tests?

**Comment by dgpetrie** [comment]
I think that you will also need to add the dataprofiler package and any other new dependencies to vcon/docker_dev/pip_package_list.txt

**Pull request closed without merging**
